name = "AXL-BOMBA"
author = "Wafflasy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65a4c23e5e73d105e3dde03b89f3060230a4c46097c42b8e3ca6cb5e7fc27e53"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"

[options]
acceptable-game-versions = ["1.12", "1.12.1", "1.12.2"]
no-internal-hashes = true
