name = "AXL-BOMBA"
author = "Wafflasy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f9571cb78caa2f8acbffe14b63b319467fb0d81daf2c93ca3d9a36747242a3f"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"

[options]
acceptable-game-versions = ["1.12", "1.12.1", "1.12.2"]
no-internal-hashes = true
