name = "AXL-BOMBA"
author = "Wafflasy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c90c176c7f53c75866a5b2cbf378586404082f5949b613de966b95fcc4d2e081"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
