name = "AXL-BOMBA"
author = "Wafflasy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e7ce7dd6376acf56cff2894bd70e74ffac95ef90afdcc82859b90f1ad7d34ba"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
