name = "AXL-BOMBA"
author = "Wafflasy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9711b1e0610f2329835366364ffffe6d43f7ec330b435122a056a41983d6b3ff"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"

[options]
acceptable-game-versions = ["1.12", "1.12.1", "1.12.2"]
no-internal-hashes = true
