name = "AXL-BOMBA"
author = "Wafflasy"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3951d11922386f284ab24505f3dfbc8b216bd13a0a9ab98502766ef668b37f20"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"

[options]
acceptable-game-versions = ["1.12", "1.12.1", "1.12.2"]
no-internal-hashes = true
