name = "AXL-BOMBA"
author = "Wafflasy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89d6c9bc9439f497d68d08c72481bb18167741c9fe659ec42b78a249358a81e8"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
